---
title: "Transporting and Flying with Drones - Notes"
subtitle: "Compiled notes on rules and regulations with transporting drones"
author: "Connor Williams"
date: 2026-08-18
format:
  html:
    toc: true
    toc-depth: 2
    number-sections: true
    theme: cosmo
    embed-resources: true
  pdf:
    toc: true
    number-sections: true
    
---

## Flying within the USA

### Flights — Carrying Batteries / Equipment {#sec-flights}

Lithium ion batteries must be in **carry-on laugage only**. It cannot be checked. This is due to the potential for these types of batteries to light on fire, which it better delt with in the cabin of the aircraft. 

From the FAA's guidance on lithium battery air travel, there are two relevent sections:

> "**Size limits**: Lithium metal (non-rechargeable) batteries are limited to 2 grams of lithium content per battery. Lithium ion (rechargeable) batteries are limited to a rating of 100 watt hours (Wh) per battery. These limits allow for nearly all types of lithium batteries used by the average person in their electronic devices. With airline approval, passengers may also carry up to two spare larger lithium ion batteries (exceeding 101–160 Wh) or Lithium metal batteries (exceeding 2-8 grams). This size covers the larger after-market extended-life laptop computer batteries and some larger batteries used in professional audio/visual equipment.

> **Quantity limits****: None for most batteries — but batteries must be for use by the passenger. Batteries carried for further sale or distribution (vendor samples, etc.) are prohibited. There is a limit of two spare batteries per person for the larger lithium ion batteries described above (exceeding 101–160 Wh per battery). Many airlines, both domestic and international, may have stricter quantity and Wh limits to include how many power banks/portable chargers each passenger is allowed to travel with, regardless of Wh capacity. Please check with your air carrier for its specific restrictions before traveling."

The DJI mini 4 Pro battery specs are as follows:

- Max Charge Voltage: 8.5 V
- Rated Capacity: 28.41 Wh, 3850 mAh
- Nominal Voltage: 7.38 Vdc

Since they are smaller then the large lithium ion battery limit, one person should be able to carry more then 2 spare batteries. We'd need to make sure it is clear that they are being used for personal use and not for resell of anykind. 

Reddit sources seem to collaberate these findings. They've said that they've had no problems transporting the the drone itself. TSA was only concerned about the batteries, and as long as they were in their carry-ons there was no problem. 

— [FAA PackSafe: Lithium Batteries](https://www.faa.gov/hazmat/packsafe/lithium-batteries)

Reddit Sources: [1](https://www.reddit.com/r/drones/comments/1hx6ymy/can_i_fly_with_my_drone_on_my_carry_on/), [2](https://www.reddit.com/r/dji/comments/172575g/transporting_drone_on_an_airplane/), [3](https://www.reddit.com/r/ecuador/comments/1e8tnf9/drone_regulations/)

## International Flights

When leaving the county, make sure to fill out the [FAA CBP Form 4457](https://www.cbp.gov/document/forms/form-4457-certificate-registration-personal-effects-taken-abroad) to show that the drone was bought in the US. This will help avoid any questions when coming back into the US. Prior to Departure, the drone and the completed form will need to be presented to a CBP Officer for comparison and signing of the form.

It looks like this has to be done at a CBP office. The only one in Utah is at the Salt Lake Airport, as seen [here](https://www.cbp.gov/about/contact/ports/UT).

Here is a DJI source about some [Airline Baggage Battery Policies](https://www.dji.com/flyingtips/airlines).